---
- name: Make sure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: true

- name: Make sure all homebrew taps are present
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ taps }}'

- name: Make sure all apps
  homebrew:
    name: '{{ apps }}'
    state: present

- name: Make sure all homebrew cask applications are present
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: '{{ cask_apps }}'
