---
# homebrew apps
apps:
  - wget
  - tree
  - zsh
  - zsh-completions
  - ag
  - tig
  - sbt
  - htop

# homebrew cask apps
cask_apps:
  # Browsers
  - google-chrome

  # Media
  - spotify
  - vlc

  # VPN
  - tunnelblick

  # Dev
  - iterm2
  - java
  - intellij-idea-ce

  # Miscellaneous
  - spectacle
  - osxfuse
  - veracrypt
  - telegram
  - transmission
