---
- name: Make sure tmux is present
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - tmux
    - reattach-to-user-namespace

- name: Make sure config folders are present
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tmux_path }}'
    - '{{ tmux_path }}/plugins'

- name: Make sure tmp is present
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '{{ tmux_path }}/plugins/tpm'
    depth: 1

- name: Make sure .tmux.conf is present
  template:
    src: templates/.tmux.conf.j2
    dest: '{{ tmux_config_path }}'
